name: cv_builder
description: A Flutter app to build resumes and export PDF.
publish_to: "none" # Private package

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  pdf: ^3.11.0
  printing: ^5.11.0
  path_provider: ^2.0.15
  share_plus: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Put your app logo or images here
